name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
        
    steps:
    - uses: actions/checkout@v4
    - name: Build and Test
      run: |
        cmake -S . -B build
        cmake --build build
        ./build/main
        ./build/unitTest
