name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
        
    steps:
    - uses: actions/checkout@v4
    - name: Build and Test
      run: |
        cmake -S . -B build -DCMAKE_PREFIX_PATH=/home/alimabna/or-tools/install
        cmake --build build
        ./build/main "test_data.vrp"
        ./build/unitTest